<?php

declare(strict_types=1);

use App\Controllers\AdminAuthController;
use App\Controllers\AdminController;
use App\Controllers\CatalogController;
use App\Controllers\ContactController;
use App\Controllers\HomeController;
use App\Controllers\PageController;
use App\Controllers\ProductController;
use App\Repositories\CategoryRepository;
use App\Repositories\ComponentRepository;
use App\Repositories\ContactRequestRepository;
use App\Repositories\HomeSlideRepository;
use App\Repositories\MenuItemRepository;
use App\Repositories\PageRepository;
use App\Repositories\ProductBomRepository;
use App\Repositories\ProductImageRepository;
use App\Repositories\ProductRepository;
use App\Repositories\SettingRepository;
use App\Services\AdminAuthService;
use App\Services\CategoryService;
use App\Services\BrandingService;
use App\Services\ComponentService;
use App\Services\ContactService;
use App\Services\HomeSlideService;
use App\Services\MenuService;
use App\Services\PageService;
use App\Services\ProductBomService;
use App\Services\ProductImageService;
use App\Services\ProductService;

$categoryService = new CategoryService(new CategoryRepository($flight->get('db')));
$componentRepository = new ComponentRepository($flight->get('db'));
$componentService = new ComponentService($componentRepository);
$contactService = new ContactService(new ContactRequestRepository($flight->get('db')));
$slideService = new HomeSlideService(new HomeSlideRepository($flight->get('db')));
$brandingService = new BrandingService(new SettingRepository($flight->get('db')));
$menuService = new MenuService(new MenuItemRepository($flight->get('db')));
$productImageRepository = new ProductImageRepository($flight->get('db'));
$productRepository = new ProductRepository($flight->get('db'));
$productService = new ProductService($productRepository, $productImageRepository);
$productBomService = new ProductBomService(new ProductBomRepository($flight->get('db')), $productRepository, $componentRepository);
$productImageService = new ProductImageService($productImageRepository);
$pageService = new PageService(new PageRepository($flight->get('db')));
$adminAuth = $flight->get('adminAuth');
$adminController = new AdminController($view, $adminAuth, $categoryService, $productService, $productImageService, $contactService, $componentService, $productBomService, $slideService, $brandingService, $menuService, $pageService);
$adminAuthController = new AdminAuthController($view, $adminAuth);
$contactController = new ContactController($view, $contactService, $pageService);

$flight->route('GET /', [new HomeController($view, $categoryService, $productService, $slideService), 'index']);
$flight->route('GET /catalogo', [new CatalogController($view, $categoryService, $productService, $pageService), 'index']);
$flight->route('GET /categoria/@slug', [new CatalogController($view, $categoryService, $productService, $pageService), 'category']);
$flight->route('GET /prodotto/@slug', [new ProductController($view, $productService, $productImageService), 'show']);
$pageController = new PageController($view, $pageService, $productService);

$flight->route('GET /laboratorio', static function () use ($pageController): void {
    $pageController->show('laboratorio');
});
$flight->route('GET /personalizzazioni', static function () use ($pageController): void {
    $pageController->show('personalizzazioni');
});
$flight->route('GET /scopri/@slug', static function (string $slug) use ($pageController): void {
    $pageController->show($slug);
});
$flight->route('GET /admin/login', [$adminAuthController, 'login']);
$flight->route('POST /admin/login', [$adminAuthController, 'authenticate']);
$flight->route('POST /admin/logout', [$adminAuthController, 'logout']);
$flight->route('GET /admin', [$adminController, 'dashboard']);
$flight->route('GET /admin/categorie', [$adminController, 'categories']);
$flight->route('GET /admin/categorie/@categoryId/modifica', [$adminController, 'editCategory']);
$flight->route('POST /admin/categorie', [$adminController, 'storeCategory']);
$flight->route('POST /admin/categorie/@categoryId/modifica', [$adminController, 'updateCategory']);
$flight->route('POST /admin/categorie/@categoryId/immagine', [$adminController, 'uploadCategoryImage']);
$flight->route('POST /admin/categorie/@categoryId/elimina', [$adminController, 'deleteCategory']);
$flight->route('GET /admin/prodotti', [$adminController, 'products']);
$flight->route('GET /admin/prodotti/nuovo', [$adminController, 'newProduct']);
$flight->route('POST /admin/prodotti', [$adminController, 'storeProduct']);
$flight->route('GET /admin/prodotti/@productId/modifica', [$adminController, 'editProduct']);
$flight->route('POST /admin/prodotti/@productId/modifica', [$adminController, 'updateProduct']);
$flight->route('POST /admin/prodotti/@productId/elimina', [$adminController, 'deleteProduct']);
$flight->route('POST /admin/prodotti/@productId/distinta-base', [$adminController, 'storeBomItem']);
$flight->route('POST /admin/distinta-base/@bomItemId/elimina', [$adminController, 'deleteBomItem']);
$flight->route('POST /admin/prodotti/@productId/immagini', [$adminController, 'uploadProductImage']);
$flight->route('POST /admin/prodotti/@productId/immagini/esistenti', [$adminController, 'attachExistingProductImage']);
$flight->route('POST /admin/immagini/@imageId/principale', [$adminController, 'makePrimaryProductImage']);
$flight->route('POST /admin/immagini/@imageId/rimuovi', [$adminController, 'removeProductImage']);
$flight->route('GET /admin/componenti', [$adminController, 'components']);
$flight->route('GET /admin/componenti/@componentId/modifica', [$adminController, 'editComponent']);
$flight->route('POST /admin/componenti', [$adminController, 'storeComponent']);
$flight->route('POST /admin/componenti/@componentId/modifica', [$adminController, 'updateComponent']);
$flight->route('POST /admin/componenti/@componentId/elimina', [$adminController, 'deleteComponent']);
$flight->route('GET /admin/slides', [$adminController, 'slides']);
$flight->route('GET /admin/menu', [$adminController, 'menu']);
$flight->route('GET /admin/pagine', [$adminController, 'pages']);
$flight->route('GET /admin/pagine/@pageId/modifica', [$adminController, 'editPage']);
$flight->route('GET /admin/menu/@itemId/modifica', [$adminController, 'editMenuItem']);
$flight->route('POST /admin/pagine/@pageId/modifica', [$adminController, 'updatePage']);
$flight->route('POST /admin/pagine/@pageId/immagine', [$adminController, 'uploadPageImage']);
$flight->route('POST /admin/menu', [$adminController, 'storeMenuItem']);
$flight->route('POST /admin/menu/@itemId/modifica', [$adminController, 'updateMenuItem']);
$flight->route('POST /admin/menu/@itemId/immagine', [$adminController, 'uploadMenuItemImage']);
$flight->route('POST /admin/menu/@itemId/su', [$adminController, 'moveMenuItemUp']);
$flight->route('POST /admin/menu/@itemId/giu', [$adminController, 'moveMenuItemDown']);
$flight->route('POST /admin/menu/@itemId/elimina', [$adminController, 'deleteMenuItem']);
$flight->route('GET /admin/slides/@slideId/modifica', [$adminController, 'editSlide']);
$flight->route('POST /admin/slides', [$adminController, 'storeSlide']);
$flight->route('POST /admin/slides/@slideId/modifica', [$adminController, 'updateSlide']);
$flight->route('POST /admin/slides/@slideId/elimina', [$adminController, 'deleteSlide']);
$flight->route('GET /admin/branding', [$adminController, 'branding']);
$flight->route('POST /admin/branding/logo', [$adminController, 'updateBrandingLogo']);
$flight->route('GET /admin/contatti', [$adminController, 'contacts']);
$flight->route('POST /admin/contatti/@requestId/stato', [$adminController, 'updateContactStatus']);
$flight->route('GET /contatti', [$contactController, 'index']);
$flight->route('POST /contatti', [$contactController, 'submit']);
